### PR TITLE
Update -b flag to work on linux

### PR DESCRIPTION
**Pull request by aturkewi**
Add linux command to open chrome and add check to see if command
is being run on linux. Up rev'd to 2.1.3

@loganhasson @peterbell

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey @aturkewi is this something we should look at or did you say someone else had a PR for this? Let me know. Also, I'll have to defer to @loganhasson as he knows how the gem works 😄

**Comment by loganhasson** [comment]
hey @aturkewi sorry, had to make a few changes so that this would work at all on the ILE and created some conflicts that'll need to be resolved before we can merge.

**Comment by loganhasson** [comment]
thanks @aturkewi !!

**Comment by PeterBell** [comment]
w00t - thanks @loganhasson and @aturkewi awesome to get a fix in!

**Pull request merged**
